version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n-main
    restart: unless-stopped
    # ⚠️ COOLIFY : Ne pas exposer les ports publiquement, Coolify gère le routage
    # ports:
    #   - "5678:5678"  # Commenté pour Coolify
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https  # ✅ Changé en HTTPS pour Coolify
      # 🔹 Remplace par ton domaine Coolify (ex: n8n.tondomaine.com)
      - WEBHOOK_URL=https://n8n.dbyway.com  
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - NODE_OPTIONS=--max-old-space-size=2048
      - N8N_METRICS=true
    volumes:
      # ✅ Coolify préfère les volumes nommés
      - n8n_data:/home/node/.n8n
      - n8n_files:/files
      - ./mcp-config:/home/node/.n8n/mcp-config:ro
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - n8n-mcp-network
    labels:
      # 🔹 Labels Coolify pour le routage automatique
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.port=5678"

  playwright:
    image: mcr.microsoft.com/playwright:v1.40.0-focal
    container_name: n8n-playwright
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
    shm_size: 2gb
    environment:
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
      - NODE_OPTIONS=--max-old-space-size=1024
    volumes:
      - playwright_browsers:/ms-playwright
      - playwright_cache:/tmp
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
        reservations:
          cpus: '0.5'
          memory: 1G
    command: tail -f /dev/null
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Playwright container is healthy')"]
      interval: 60s
      timeout: 10s
      retries: 2
    networks:
      - n8n-mcp-network

  mcp-server:
    image: node:18-bullseye
    container_name: n8n-mcp-server
    restart: unless-stopped
    # ⚠️ COOLIFY : Ports commentés
    # ports:
    #   - "8080:8080"
    environment:
      - NODE_ENV=production
      - MCP_PORT=8080
      - MCP_LOG_LEVEL=info
    volumes:
      - ./mcp-server:/app
      - mcp_logs:/var/log/mcp
    working_dir: /app
    command: sh -c "apt-get update && apt-get install -y curl && npm install && npx playwright install --with-deps chromium && node server.js"
    depends_on:
      playwright:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - n8n-mcp-network
    labels:
      # 🔹 Labels Coolify pour exposer MCP server
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.port=8080"

volumes:
  n8n_data:
    driver: local
  n8n_files:
    driver: local
  playwright_browsers:
    driver: local
  playwright_cache:
    driver: local
  mcp_logs:
    driver: local

networks:
  default:
    name: n8n-mcp-network
    driver: bridge
